

name: CI


on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3


      - name: Run a one-line script
        run: echo Hello, world!


      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifacts

 
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
          path: ./downloaded
