# installer.yml (fixed & consistent)

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # Upload artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: installer-artifact
          path: path/to/artifacts

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3

      # Download the same artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: installer-artifact
          path: ./downloaded
